// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4kzM8FNq9HFHiSYwV0KsQtAf5fXG1Ozc',
    appId: '1:971192083180:web:e336e538f3eb0943d3fbc9',
    messagingSenderId: '971192083180',
    projectId: 'propsure-d8f44',
    authDomain: 'propsure-d8f44.firebaseapp.com',
    storageBucket: 'propsure-d8f44.firebasestorage.app',
    measurementId: 'G-HQJ8CYBBEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Zc_7qnwaxOzw0-7DV3UI49UuFGujrI0',
    appId: '1:971192083180:android:3d516d783a1bbbb0d3fbc9',
    messagingSenderId: '971192083180',
    projectId: 'propsure-d8f44',
    storageBucket: 'propsure-d8f44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9c2vCqIfMZhsePFruwmToduyqVjiYiPE',
    appId: '1:971192083180:ios:7bf96706ed35f0fcd3fbc9',
    messagingSenderId: '971192083180',
    projectId: 'propsure-d8f44',
    storageBucket: 'propsure-d8f44.firebasestorage.app',
    iosBundleId: 'com.propsure.propsure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9c2vCqIfMZhsePFruwmToduyqVjiYiPE',
    appId: '1:971192083180:ios:7bf96706ed35f0fcd3fbc9',
    messagingSenderId: '971192083180',
    projectId: 'propsure-d8f44',
    storageBucket: 'propsure-d8f44.firebasestorage.app',
    iosBundleId: 'com.propsure.propsure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4kzM8FNq9HFHiSYwV0KsQtAf5fXG1Ozc',
    appId: '1:971192083180:web:ca89af2a539cf3f9d3fbc9',
    messagingSenderId: '971192083180',
    projectId: 'propsure-d8f44',
    authDomain: 'propsure-d8f44.firebaseapp.com',
    storageBucket: 'propsure-d8f44.firebasestorage.app',
    measurementId: 'G-T1GRCMEQ01',
  );
}
